### ISSUE TITLE
Create players template page

### ISSUE THREAD

**Issue by NicholasEwing** [NicholasEwing/bubble-tea-league#12]
Create our players page with basic info on each player such as:
- Summoner name
- Team role
- Lifetime kills / deaths / assists / gold earned, etc. (keep it super simple for now just so we get the page up, we can be more specific once the API works)

This page should also be a template that has info filled with some placeholder dummy data.

Otherwise, we'd end up managing and hard-coding potentially hundreds of separate HTML files.

**Comment by mayurstwt** [comment]
I would love to work on this issue would you please assign me this ?
