### ISSUE TITLE
Make navbar global

### ISSUE THREAD

**Issue by NicholasEwing** [NicholasEwing/bubble-tea-league#6]
Instead of having to repeat the HTML for our navigation bar, write a JavaScript function that will automatically insert the header on each page.

This allows us to manage our HTML in one place, rather than updating every individual page when we want to change something.

**Comment by Mahad410** [comment]
I want to contribute to your project but with Jquery so can you assign this to me

**Comment by NicholasEwing** [comment]
Hey @Mahad410, I'll be working on this exclusively with my friend Chase. Sorry!

In the meantime, you're welcome to browse our code and comment on anything you have questions about and I'd be glad to explain some things.
