### ISSUE TITLE
Make footer global

### ISSUE THREAD

**Issue by NicholasEwing** [NicholasEwing/bubble-tea-league#7]
Instead of having to repeat the HTML for our footer, write a JavaScript function that will automatically insert the footer on each page.

This allows us to manage our HTML in one place, rather than updating every individual page when we want to change something.

All tasks for this issue:
- [ ] Make the @NicholasEwing / @ChaseH38 mentions on the footer link to our Github profiles (to flex)
- [ ] Make the Github logo on the right side of the footer link to this Github repo (same as the one in the navbar)
- [ ] Rename the "Bubble Tea Stats Tracker" text to just "Bubble Tea League"
- [ ] Finally, create a single `<footer>` tag on each HTML page and write a JavaScript function called `loadFooter()` that will insert the HTML for the footer inside the `<footer>` tag (use the `loadNavbar()` function and `<nav>` tag on each HTML page as reference, it's literally doing the same thing except it's a footer so you can mostly copy / paste from `loadNavbar()`)

**Comment by Mahad410** [comment]
I want to contribute to your project but with Jquery so can you assign this to me

**Comment by NicholasEwing** [comment]
Hey @Mahad410, I'll be working on this exclusively with my friend Chase. Sorry!

In the meantime, you're welcome to browse our code and comment on anything you have questions about and I'd be glad to explain some things.

**Comment by Mahad410** [comment]
sure thing @NicholasEwing
